<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Alephs-MacBook-Pro.local" failures="3" tests="3" name="invalidPost" time="0.987" errors="0" timestamp="2023-03-19T13:45:16 ICT">
  <testcase classname="demo.Example2Test" name="TC01_StatusCodeTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Status check failed expected [401] but found [201]">
      <![CDATA[java.lang.AssertionError: Status check failed expected [401] but found [201]
at demo.Example2Test.TC01_StatusCodeTest(Example2Test.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- TC01_StatusCodeTest -->
  <testcase classname="demo.Example2Test" name="TC02_MessageChecked" time="0.001">
    <failure type="java.lang.AssertionError" message="Message field check failed expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Message field check failed expected [false] but found [true]
at demo.Example2Test.TC02_MessageChecked(Example2Test.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- TC02_MessageChecked -->
  <testcase classname="demo.Example2Test" name="TC03_verifyOnMessageContainName" time="0.009">
    <failure type="java.lang.AssertionError" message="Message not contain invalid field expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Message not contain invalid field expected [false] but found [true]
at demo.Example2Test.TC03_verifyOnMessageContainName(Example2Test.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- TC03_verifyOnMessageContainName -->
</testsuite> <!-- invalidPost -->
